### ISSUE TITLE
[BUG] Compile warnings in tests/hash.cpp

### ISSUE THREAD

**Issue by thirtiseven** [NVIDIA/spark-rapids-jni#1864] opened 2024-03-12 09:58 UTC
We have some compile warnings when building current code that need to be addressed:
```
warning: 'std::unique_ptr<cudf::column> cudf::hash(const cudf::table_view&, cudf::hash_id, uint32_t, rmm::cuda_stream_view, rmm::mr::device_memory_resource*)' is deprecated [-Wdeprecated-declarations]
```
in `tests/hash.cpp`.

`cudf::hash` was deprecated in https://github.com/rapidsai/cudf/pull/15074 a few weeks ago and `cudf::hashing::hash()` will be removed in a follow-on release.

**Comment by mattahrens** [comment] 2024-03-12 20:35
Duplicate of https://github.com/NVIDIA/spark-rapids/issues/10487

**Closed by mattahrens** 2024-03-12 20:35 UTC
Labels: bug
